services:
  node:
    platform: linux/amd64
    image: "node:22"
    container_name: front-events
    user: "node"
    working_dir: /node/app
    volumes:
      - ./:/node/app
    networks:
      - front-events-network
    ports:
      - "8081:8081"
    command: "npm run dev"

networks:
  front-events-network:
    driver: bridge